config/routes.rb
Rails.application.routes.draw do
  resources :drink_dict_items
  resources :food_dict_items
  get 'cafe/index'

  resources :c_tables
  resources :orders
  resources :clients
  resources :waitresses do
    resources :orders
  end

  resources :drinks
  resources :foods

  root to: 'cafe#index', as: 'cafe'

end

app/controllers/waitresses_controller.rb
class WaitressesController < ApplicationController
  before_action :set_waitress, only: [:show, :edit, :update, :destroy]

  # GET /waitresses
  # GET /waitresses.json
  def index
    @waitresses = Waitress.all
  end

  # GET /waitresses/1
  # GET /waitresses/1.json
  def show
  end

  # GET /waitresses/new
  def new
    @waitress = Waitress.new
  end

  # GET /waitresses/1/edit
  def edit
  end

  # POST /waitresses
  # POST /waitresses.json
  def create
    @waitress = Waitress.new(waitress_params)

    respond_to do |format|
      if @waitress.save
        format.html { redirect_to @waitress, notice: 'Waitress was successfully created.' }
        format.json { render :show, status: :created, location: @waitress }
      else
        format.html { render :new }
        format.json { render json: @waitress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitresses/1
  # PATCH/PUT /waitresses/1.json
  def update
    respond_to do |format|
      if @waitress.update(waitress_params)
        format.html { redirect_to @waitress, notice: 'Waitress was successfully updated.' }
        format.json { render :show, status: :ok, location: @waitress }
      else
        format.html { render :edit }
        format.json { render json: @waitress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitresses/1
  # DELETE /waitresses/1.json
  def destroy
    @waitress.destroy
    respond_to do |format|
      format.html { redirect_to waitresses_url, notice: 'Waitress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitress
      @waitress = Waitress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waitress_params
      params.require(:waitress).permit(:fullname)
    end
end

app/helpers/waitresses_helper.rb
module WaitressesHelper
end

app/views/waitresses/_form.html.erb
<%= form_for(@waitress) do |f| %>
  <% if @waitress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waitress.errors.count, "error") %> prohibited this waitress from being saved:</h2>

      <ul>
      <% @waitress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waitresses/edit.html.erb
<h1>Editing Waitress</h1>

<%= render 'form' %>

<%= link_to 'Show', @waitress %> |
<%= link_to 'Back', waitresses_path %>

app/views/waitresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Waitresses</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitresses.each do |waitress| %>
      <tr>
        <td><%= waitress.fullname %></td>
        <td><%= link_to 'Show', waitress %></td>
        <td><%= link_to 'Edit', edit_waitress_path(waitress) %></td>
        <td><%= link_to 'Destroy', waitress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waitress', new_waitress_path %>

app/views/waitresses/new.html.erb
<h1>New Waitress</h1>

<%= render 'form' %>

<%= link_to 'Back', waitresses_path %>

app/views/waitresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @waitress.fullname %>
</p>

<%= link_to 'Edit', edit_waitress_path(@waitress) %> |
<%= link_to 'Back', waitresses_path %>