config/routes.rb
Rails.application.routes.draw do
  resources :drink_dict_items
  resources :food_dict_items
  get 'cafe/index'

  resources :c_tables
  resources :orders
  resources :clients
  resources :waitresses do
    resources :orders
  end

  resources :drinks
  resources :foods

  root to: 'cafe#index', as: 'cafe'

end

app/models/food_dict_item.rb
class FoodDictItem < ActiveRecord::Base
  validates :title, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
end

app/controllers/food_dict_items_controller.rb
class FoodDictItemsController < ApplicationController
  before_action :set_food_dict_item, only: [:show, :edit, :update, :destroy]

  # GET /food_dict_items
  # GET /food_dict_items.json
  def index
    @food_dict_items = FoodDictItem.all
  end

  # GET /food_dict_items/1
  # GET /food_dict_items/1.json
  def show
  end

  # GET /food_dict_items/new
  def new
    @food_dict_item = FoodDictItem.new
  end

  # GET /food_dict_items/1/edit
  def edit
  end

  # POST /food_dict_items
  # POST /food_dict_items.json
  def create
    @food_dict_item = FoodDictItem.new(food_dict_item_params)

    respond_to do |format|
      if @food_dict_item.save
        format.html { redirect_to @food_dict_item, notice: 'Food dict item was successfully created.' }
        format.json { render :show, status: :created, location: @food_dict_item }
      else
        format.html { render :new }
        format.json { render json: @food_dict_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_dict_items/1
  # PATCH/PUT /food_dict_items/1.json
  def update
    respond_to do |format|
      if @food_dict_item.update(food_dict_item_params)
        format.html { redirect_to @food_dict_item, notice: 'Food dict item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_dict_item }
      else
        format.html { render :edit }
        format.json { render json: @food_dict_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_dict_items/1
  # DELETE /food_dict_items/1.json
  def destroy
    @food_dict_item.destroy
    respond_to do |format|
      format.html { redirect_to food_dict_items_url, notice: 'Food dict item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_dict_item
      @food_dict_item = FoodDictItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_dict_item_params
      params.require(:food_dict_item).permit(:title, :price)
    end
end

app/helpers/food_dict_items_helper.rb
module FoodDictItemsHelper
end

app/views/food_dict_items/_form.html.erb
<%= form_for(@food_dict_item) do |f| %>
  <% if @food_dict_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_dict_item.errors.count, "error") %> prohibited this food_dict_item from being saved:</h2>

      <ul>
      <% @food_dict_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_dict_items/edit.html.erb
<h1>Editing Food Dict Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_dict_item %> |
<%= link_to 'Back', food_dict_items_path %>

app/views/food_dict_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Dict Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_dict_items.each do |food_dict_item| %>
      <tr>
        <td><%= food_dict_item.title %></td>
        <td><%= food_dict_item.price %></td>
        <td><%= link_to 'Show', food_dict_item %></td>
        <td><%= link_to 'Edit', edit_food_dict_item_path(food_dict_item) %></td>
        <td><%= link_to 'Destroy', food_dict_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food dict item', new_food_dict_item_path %>

app/views/food_dict_items/new.html.erb
<h1>New Food Dict Item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_dict_items_path %>

app/views/food_dict_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @food_dict_item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_dict_item.price %>
</p>

<%= link_to 'Edit', edit_food_dict_item_path(@food_dict_item) %> |
<%= link_to 'Back', food_dict_items_path %>