config/routes.rb
Rails.application.routes.draw do
  resources :drink_dict_items
  resources :food_dict_items
  get 'cafe/index'

  resources :c_tables
  resources :orders
  resources :clients
  resources :waitresses do
    resources :orders
  end

  resources :drinks
  resources :foods

  root to: 'cafe#index', as: 'cafe'

end

app/controllers/c_tables_controller.rb
class CTablesController < ApplicationController
  before_action :set_c_table, only: [:show, :edit, :update, :destroy]

  # GET /c_tables
  # GET /c_tables.json
  def index
    @c_tables = CTable.all
  end

  # GET /c_tables/1
  # GET /c_tables/1.json
  def show
  end

  # GET /c_tables/new
  def new
    @c_table = CTable.new
  end

  # GET /c_tables/1/edit
  def edit
  end

  # POST /c_tables
  # POST /c_tables.json
  def create
    @c_table = CTable.new(c_table_params)

    respond_to do |format|
      if @c_table.save
        format.html { redirect_to @c_table, notice: 'C table was successfully created.' }
        format.json { render :show, status: :created, location: @c_table }
      else
        format.html { render :new }
        format.json { render json: @c_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /c_tables/1
  # PATCH/PUT /c_tables/1.json
  def update
    respond_to do |format|
      if @c_table.update(c_table_params)
        format.html { redirect_to @c_table, notice: 'C table was successfully updated.' }
        format.json { render :show, status: :ok, location: @c_table }
      else
        format.html { render :edit }
        format.json { render json: @c_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /c_tables/1
  # DELETE /c_tables/1.json
  def destroy
    @c_table.destroy
    respond_to do |format|
      format.html { redirect_to c_tables_url, notice: 'C table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_c_table
      @c_table = CTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def c_table_params
      params.require(:c_table).permit(:number)
    end
end

app/helpers/c_tables_helper.rb
module CTablesHelper
end

app/views/c_tables/_form.html.erb
<%= form_for(@c_table) do |f| %>
  <% if @c_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@c_table.errors.count, "error") %> prohibited this c_table from being saved:</h2>

      <ul>
      <% @c_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/c_tables/edit.html.erb
<h1>Editing C Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @c_table %> |
<%= link_to 'Back', c_tables_path %>

app/views/c_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing C Tables</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @c_tables.each do |c_table| %>
      <tr>
        <td><%= c_table.number %></td>
        <td><%= link_to 'Show', c_table %></td>
        <td><%= link_to 'Edit', edit_c_table_path(c_table) %></td>
        <td><%= link_to 'Destroy', c_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New C table', new_c_table_path %>

app/views/c_tables/new.html.erb
<h1>New C Table</h1>

<%= render 'form' %>

<%= link_to 'Back', c_tables_path %>

app/views/c_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @c_table.number %>
</p>

<%= link_to 'Edit', edit_c_table_path(@c_table) %> |
<%= link_to 'Back', c_tables_path %>